from nnUtils import *

model = Sequential([
    BinarizedWeightOnlySpatialConvolution(128,3,3,1,1, padding='SAME', bias=False),
    batch_normalization(),
    HardTanh(),
    BinarizedSpatialConvolution(128,3,3, padding='SAME', bias=False),
    SpatialMaxPooling(2,2,2,2),
    batch_normalization(),
    HardTanh(),
    BinarizedSpatialConvolution(256,3,3, padding='SAME', bias=False),
    batch_normalization(),
    HardTanh(),
    BinarizedSpatialConvolution(256,3,3, padding='SAME', bias=False),
    SpatialMaxPooling(2,2,2,2),
    batch_normalization(),
    HardTanh(),
    BinarizedSpatialConvolution(512,3,3, padding='SAME', bias=False),
    batch_normalization(),
    HardTanh(),
    BinarizedSpatialConvolution(512,3,3, padding='SAME', bias=False),
    SpatialMaxPooling(2,2,2,2),
    batch_normalization(),
    HardTanh(),
    BinarizedAffine(1024, bias=False),
    batch_normalization(),
    HardTanh(),
    BinarizedAffine(1024, bias=False),
    batch_normalization(),
    HardTanh(),
    BinarizedAffine(10, bias=False),
    batch_normalization()
])
